### ISSUE TITLE
Handle failure of mongoDB server

### ISSUE THREAD

**Issue by g2valdez** [everyone-counts/mongo-stream#19]
If the MongoDB server fails, detect the event, and retry connection to the database on a set interval.

**Comment by docon001** [comment]
After computer hibernation this error logs:

changeStream error { MongoError: pool destroyed
    at Pool.write (/root/mongo-stream/node_modules/mongodb-core/lib/connection/pool.js:1118:12)
    at WireProtocol.getMore (/root/mongo-stream/node_modules/mongodb-core/lib/wireprotocol/3_2_support.js:277:14)
    at Cursor._getmore (/root/mongo-stream/node_modules/mongodb-core/lib/cursor.js:323:35)
    at nextFunction (/root/mongo-stream/node_modules/mongodb-core/lib/cursor.js:696:10)
    at /root/mongo-stream/node_modules/mongodb-core/lib/cursor.js:731:7
    at queryCallback (/root/mongo-stream/node_modules/mongodb-core/lib/wireprotocol/3_2_support.js:245:5)
    at /root/mongo-stream/node_modules/mongodb-core/lib/connection/pool.js:541:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9) name: 'MongoError', message: 'pool destroyed' }
close event
